### ISSUE TITLE
/usr/lib/tmpfiles.d/opendkim.conf path points to /var/run/ instead of /run

### ISSUE THREAD

**Issue by wizwuz** [trusteddomainproject/OpenDKIM#38] opened 2019-03-13 11:47 UTC
System:
Debian buster/sid via Raspbian

OpenDKIM: 
opendkim: OpenDKIM Filter v2.11.0
        Compiled with OpenSSL 1.1.1b  26 Feb 2019
        SMFI_VERSION 0x1000001
        libmilter version 1.0.1
        Supported signing algorithms:
                rsa-sha1
                rsa-sha256
        Supported canonicalization algorithms:
                relaxed
                simple
        Active code options:
                POLL
                QUERY_CACHE
                USE_DB
                USE_LDAP
                USE_LUA
                USE_ODBX
                USE_UNBOUND
                _FFR_ATPS
                _FFR_RBL
                _FFR_REPLACE_RULES
                _FFR_SENDER_MACRO
                _FFR_STATS
                _FFR_VBR
        libopendkim 2.11.0: atps query_cache

Issue:
The following line is logged in syslog on startup:
[/usr/lib/tmpfiles.d/opendkim.conf:1] Line references path below legacy directory /var/run/, updating /var/run/opendkim → /run/opendkim; please update the tmpfiles.d/ drop-in file accordingly.

Looking at the tmpfiles.d config file, the content is:
rpi# cat /usr/lib/tmpfiles.d/opendkim.conf
d /var/run/opendkim 0750 opendkim opendkim - -

Path has been moved from /var/run to /run and systemd tmpfiles.d has been updated to warn when SW component still uses the old path.

OpenDKIM needs to be updated to use /run instead of /var/run for PID file.

**Comment by mskucherawy** [comment] 2019-07-24 18:11
This may be true for Debian, but not for other systems.  I guess we need to make it configurable.

**Comment by mskucherawy** [comment] 2019-07-24 18:13
If someone else could write up a patch that accepts this path via ./configure and makes use of it in our configuration files, that would be extremely helpful.

**Comment by glts** [comment] 2020-01-07 09:22
This was an open issue in the Debian package. It has now been corrected.

Nothing further to be done here.

**Comment by hdatma** [comment] 2020-07-10 19:22
Using /run instead of /var/run breaks compliance with ...
Filesystem Hierarchy Standard (FHS) 2.3 2004
http://www.pathname.com/fhs/

**Comment by lazynooblet** [comment] 2021-01-27 19:31
@hdatma -- the latest version of FHS is at https://refspecs.linuxfoundation.org/fhs.shtml which [includes /run](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html).

@glts -- the warning is from systemd and is displayed on startup in at least Fedora, Redhat, Ubuntu and Debian. Most likely in any distro that has a systemd version that includes the warning. See [downstream Redhat bug](https://bugzilla.redhat.com/show_bug.cgi?id=1915469).

**Comment by glts** [comment] 2021-07-30 14:06
The bug report was for Debian, and I was pointing out that the issue is fixed in Debian and Ubuntu. The issue reported here is no longer actionable and can be closed.

**Comment by thegushi** [comment] 2022-12-29 12:09
I believe this issue can be closed, per report from glts.

**Closed as completed by thegushi** 2022-12-29 12:09 UTC
Labels: help wanted

**Comment by WayneSallee** [comment] 2023-12-04 21:35
Ok it's 2023 now, and I am seeing this error on Debian, but don't remember seeing it before.

Should I set my config file to use /var/run/opendkim or /run/opendkim ?

  Wayne@WayneSallee.com

**Comment by hdatma** [comment] 2024-03-11 09:37
> @hdatma -- the latest version of FHS is at https://refspecs.linuxfoundation.org/fhs.shtml which [includes /run](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html).

Still leave it as an option, as systems like OpenBSD do not have /run.
